(self.AMP=self.AMP||[]).push({n:"amp-anim",ev:"0.1",l:true,v:"2104081613001",m:0,f:(function(AMP,_){
'use strict';var d="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function k(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var e=b[c];if(e&&e.Math==Math)return}(function(){throw Error("Cannot find global object");})()}k(this);"function"===typeof Symbol&&Symbol("x");var l;
if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var m;a:{var n={a:!0},q={};try{q.__proto__=n;m=q.a;break a}catch(a){}m=!1}l=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=l;var t=self.AMP_CONFIG||{},u=("string"==typeof t.cdnProxyRegex?new RegExp(t.cdnProxyRegex):t.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function v(a){if(self.document&&self.document.head&&(!self.location||!u.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}t.cdnUrl||v("runtime-host");t.geoApiUrl||v("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var w,x="Webkit webkit Moz moz ms O o".split(" ");function y(a,b,c){var e=a.style;if(!b.startsWith("--")){w||(w=Object.create(null));var h=w[b];if(!h){h=b;if(void 0===e[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var g=0;g<x.length;g++){var p=x[g]+f;if(void 0!==e[p]){f=p;break b}}f=""}void 0!==e[f]&&(h=f)}w[b]=h}b=h}b&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}
function z(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function A(a){if(!a.hasAttribute("src")&&0=="srcset"in a){var b=a.getAttribute("srcset"),c=/\S+/.exec(b);null!=c&&a.setAttribute("src",c[0])}};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0});/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var B=new WeakMap,C=new WeakMap;function D(a,b){var c=a.ownerDocument.defaultView,e=B.get(c);if(!e){var h=B.set;var f=E;var g=void 0===g?{}:g;var p=g.needsRootBounds;f=new c.IntersectionObserver(f,{threshold:g.threshold,root:c.parent&&c.parent!=c&&p?c.document:void 0});h.call(B,c,e=f)}C.set(a,b);e.observe(a)}function E(a){for(var b=0;b<a.length;b++){var c=a[b],e=c.isIntersecting;(c=C.get(c.target))&&c(e)}};var F=["alt","aria-label","aria-describedby","aria-labelledby"],G=["src","srcset"];function H(a){a=AMP.BaseElement.call(this,a)||this;a.h=null;return a}var I=AMP.BaseElement;H.prototype=d(I.prototype);H.prototype.constructor=H;if(r)r(H,I);else for(var J in I)if("prototype"!=J)if(Object.defineProperties){var K=Object.getOwnPropertyDescriptor(I,J);K&&Object.defineProperty(H,J,K)}else H[J]=I[J];H.j=I.prototype;
H.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
H.prototype.buildCallback=function(){this.h=new Image;this.h.setAttribute("decoding","async");this.propagateAttributes(F,this.h);this.applyFillContent(this.h,!0);var a=this.element,b=this.h;a.hasAttribute("object-fit")&&y(b,"object-fit",a.getAttribute("object-fit"));a.hasAttribute("object-position")&&y(b,"object-position",a.getAttribute("object-position"));"img"==this.element.getAttribute("role")&&(this.element.removeAttribute("role"),this.user().error("AMP-ANIM","Setting role=img on amp-anim elements breaks screen readers. Please just set alt or ARIA attributes, they will be correctly propagated for the underlying <img> element."));
z(this.h,!this.getPlaceholder());this.element.appendChild(this.h)};H.prototype.isRelayoutNeeded=function(){return!0};H.prototype.layoutCallback=function(){var a=this,b=this.h;this.propagateAttributes(G,b,!0);A(b);return this.loadPromise(b).then(function(){D(a.element,function(c){a.togglePlaceholder(!c);z(a.h,c)})})};H.prototype.firstLayoutCompleted=function(){};
H.prototype.unlayoutCallback=function(){var a=this.element,b=B.get(a.ownerDocument.defaultView);b&&b.unobserve(a);C.delete(a);this.togglePlaceholder(!0);z(this.h,!1);this.h.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";this.h.srcset="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";return!0};(function(a){a.registerElement("amp-anim",H)})(self.AMP);
})});

//# sourceMappingURL=amp-anim-0.1.js.map